name: Greeter
author: Lionel R. Rivas
description: Action to greet someone
inputs:
  who-to-greet:
    description: "Person to greet"
    required: true
    default: Lionel
outputs:
  time:
    description: "The time of greeting"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
