on: push
jobs:
  custom-action-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack Github Issue Notifier
        uses: ./.github/actions/github-issue-notifier
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello From Github
      - uses: ./.github/actions/issue-creator
        id: issue-creator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: |
            lionelrrivas
      - run: |
          echo ${{ steps.issue-cretor.outputs.issue }}
      - uses: ./.github/actions/greeter
        id: greet
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.greet.outputs.time }}"
          echo $HELLO
      - uses: ./.github/actions/docker-greeter
        id: docker-greet
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.docker-greet.outputs.time }}"
          echo $HELLO
